version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=DBNAME
    networks:
      - oms_network
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  myapp:
    image: zulfijauh/oms
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=USER
      - DB_PASSWORD=PASSWORD
      - DB_NAME=DBNAME
      - DB_SSLMODE=disable
      - DB_TIMEZONE=Asia/Jakarta
    volumes:
      - './my-project:/app'
    networks:
      - oms_network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  oms_network:
    name: oms_network
